### ISSUE TITLE
Hardcoded path to sessions directory

### ISSUE THREAD

**Issue by soal** [Raghav-rv28/kitty-sesh#1]
```
$ kitty-sesh

Error reading directory: open /home/raghav/.config/kitty/sessions/: no such file or directory
```

I guess the problem is [here](https://github.com/Raghav-rv28/kitty-sesh/blob/main/main.go#L219)

**Comment by Raghav-rv28** [comment]
now isnt that a noobie mistake. the fix has been pushed. Thanks for pointing this out! feel free to test out and if you have any feature recommendations let me know!
